
include (${CMAKE_CURRENT_LIST_DIR}/CPM.cmake)

CPMFindPackage(
    NAME Open3D
    COMPONENTS Open3DCuda
    GITHUB_REPOSITORY akashsharma02/Open3D
    VERSION 0.9.0
    GIT_TAG object-slam
    OPTIONS
    "BUILD_CPP_EXAMPLES OFF"
    "BUILD_CUDA_EXAMPLES OFF"
    "BUILD_CUDA_MODULE ON"
    "BUILD_EIGEN3 OFF"
    "CUDA_WITH_OPENCV ON"
    "BUILD_PYBIND11 OFF"
    "BUILD_PYTHON_MODULE OFF"
    "BUILD_WITH_MARCH_NATIVE OFF"
    "ENABLE_JUPYTER OFF"
    )

